import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataserviceService {

  constructor() { }

  userData = [{id:1,userImage:'https://www.whatsappimages.in/wp-content/uploads/2020/06/Whatsapp-DP-Images-8-300x300.jpg',userName:'vijjy',msg:'Hai',avtiveTime:'11.9 am'},
              {id:2,userImage:'http://www.decentfashion.in/wp-content/uploads/2018/02/funny-iyimages-66-300x200.jpg',userName:'Chippa',msg:'where are you',avtiveTime:'10.45 am'},
              {id:3,userImage:'https://www.shaadidukaan.com/vogue/wp-content/uploads/2019/08/hug-kiss-images.jpg',userName:'Naresh V',msg:'coming',avtiveTime:'Yesterday'},
              {id:4,userImage:'https://pin.dekhnews.com/wp-content/uploads/2019/09/lord-shiva-images-1.jpg',userName:'Kutty',msg:'Hai',avtiveTime:'Yesterday'},
              {id:5,userImage:'https://static.remove.bg/remove-bg-web/3661dd45c31a4ff23941855a7e4cedbbf6973643/assets/start-0e837dcc57769db2306d8d659f53555feb500b3c5d456879b9c843d1872e7baa.jpg',userName:'Manam',msg:'Hai',avtiveTime:'17/7/21'},
              {id:6,userImage:'https://www.theattitudequotes.com/wp-content/uploads/2021/02/New-DP-for-instagram-Profile-Pictures-Download-2021-DP-For-Insta-29.jpg',userName:'Venkatesh G',msg:'Hai',avtiveTime:'17/7/21'},
              {id:7,userImage:'https://www.whatsappprofiledpimages.com/wp-content/uploads/2019/07/Beautiful-Cute-Whatsapp-DP-Profile-Pic-Images-52-300x300.jpg',userName:'Naresh Ch',msg:'Hai',avtiveTime:'17/7/21'},
              {id:8,userImage:'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a1573811-79e4-4830-b7a5-8b9b598e8d41/d30tard-c0878705-1dea-46ec-86de-e7bf0d39dea7.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2ExNTczODExLTc5ZTQtNDgzMC1iN2E1LThiOWI1OThlOGQ0MVwvZDMwdGFyZC1jMDg3ODcwNS0xZGVhLTQ2ZWMtODZkZS1lN2JmMGQzOWRlYTcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.HeL23Jfl2t4byG7t3dX15PUJ5GWtrsleR5flaqGAENo',userName:'Sai Mama',msg:'Hai',avtiveTime:'16/7/21'},
              {id:9,userImage:'https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/06/27/15/tom-sodoge-59546-0.jpg',userName:'Kattappa',msg:'Hai',avtiveTime:'16/7/21'},
              {id:10,userImage:'https://wallpapercave.com/wp/wp2976783.jpg',userName:'30Lakhs',msg:'Hai',avtiveTime:'16/7/21'},
              {id:11,userImage:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfKb-d1LFsAZ63BEiu_eH_-S8ZmLTgnre4_Q&usqp=CAU',userName:'9966620242',msg:'Hai',avtiveTime:'15/7/21'},
              {id:12,userImage:'https://www.advertisemint.com/wp-content/uploads/2017/03/view-facebook-profile-looks-like-to-others-binoculars-spying.jpg',userName:'Prashanth G',msg:'Hai',avtiveTime:'15/7/21'},
              {id:13,userImage:'https://i.pinimg.com/236x/ed/6c/38/ed6c382b3bf83cba46adb1efec0e49b6.jpg',userName:'Shivalayam Youth',msg:'Hai',avtiveTime:'14/7/21'},
              {id:14,userImage:'https://ath2.unileverservices.com/wp-content/uploads/sites/3/2017/08/hair-mousse-for-men-thick-pomp.jpg',userName:'Cnu Ch',msg:'Hai',avtiveTime:'14/7/21'},
              {id:15,userImage:'https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg',userName:'Chintu',msg:'Hai',avtiveTime:'12/7/21'},
              {id:16,userImage:'http://s4.thingpic.com/images/s4/eJUVBCxdW6z47vVFBEgAQkTz.jpeg',userName:'Ramesh A',msg:'Hai',avtiveTime:'12/7/21'},
              {id:17,userImage:'https://adhurihasrate.in/wp-content/uploads/2020/12/sad-whatsapp-profile-pic-28-1024x1024.jpeg',userName:'Laxmareddy',msg:'Hai',avtiveTime:'11/7/21'},
              {id:18,userImage:'https://1.bp.blogspot.com/-LmfHmn0vowU/X4yEzgh6DHI/AAAAAAAAfOw/E1PI8dCa2qkBSPiDtSy6xUi2unxdQoUrACLcBGAsYHQ/s2048/sad%2Bdp%2B%25281%2529.jpg',userName:'Sathish E',msg:'Hai',avtiveTime:'11/7/21'},
              {id:19,userImage:'https://data.whicdn.com/images/111250986/original.png',userName:'Shekar Boora',msg:'Hai',avtiveTime:'10/7/21'},
              {id:20,userImage:'https://carryquotes.com/wp-content/uploads/2021/04/1619138243_773_Profile-Picture-127-Whatsapp-Profile-Picture-Download-Good-Morning.jpg',userName:'Rakesh',msg:'Hai',avtiveTime:'10/7/21'},
              {id:21,userImage:'https://www.shaadidukaan.com/vogue/wp-content/uploads/2019/08/hug-kiss-images.jpg',userName:'Babai',msg:'Hai',avtiveTime:'10/7/21'}]
  gettigUserdata(){
    return this.userData
  }

  Emojis = [{id:1,emoji:'assets/img/emojis/emoji1.png'},{id:2,emoji:'assets/img/emojis/emoji2.png'},{id:3,emoji:'assets/img/emojis/emoji3.png'},{id:4,emoji:'assets/img/emojis/emoji4.png'},
            {id:5,emoji:'assets/img/emojis/emoji5.png'},{id:6,emoji:'assets/img/emojis/emoji6.png'},{id:7,emoji:'assets/img/emojis/emoji7.png'},{id:8,emoji:'assets/img/emojis/emoji8.png'},
            {id:9,emoji:'assets/img/emojis/emoji9.png'},{id:10,emoji:'assets/img/emojis/emoji10.png'},{id:11,emoji:'assets/img/emojis/emoji11.png'},{id:12,emoji:'assets/img/emojis/emoji12.png'},
            {id:13,emoji:'assets/img/emojis/emoji13.png'},{id:14,emoji:'assets/img/emojis/emoji14.png'},{id:15,emoji:'assets/img/emojis/emoji15.png'},{id:16,emoji:'assets/img/emojis/emoji16.png'},
            {id:17,emoji:'assets/img/emojis/emoji17.png'},{id:18,emoji:'assets/img/emojis/emoji18.png'},{id:19,emoji:'assets/img/emojis/emoji19.png'},{id:20,emoji:'assets/img/emojis/emoji20.png'},
            {id:21,emoji:'assets/img/emojis/emoji21.png'},{id:22,emoji:'assets/img/emojis/emoji22.png'},{id:23,emoji:'assets/img/emojis/emoji23.png'},{id:24,emoji:'assets/img/emojis/emoji24.png'},
            {id:25,emoji:'assets/img/emojis/emoji25.png'},{id:26,emoji:'assets/img/emojis/emoji26.png'},{id:27,emoji:'assets/img/emojis/emoji27.png'},{id:28,emoji:'assets/img/emojis/emoji28.png'},
            {id:29,emoji:'assets/img/emojis/emoji29.png'},{id:30,emoji:'assets/img/emojis/emoji30.png'},{id:31,emoji:'assets/img/emojis/emoji31.png'},{id:32,emoji:'assets/img/emojis/emoji32.png'},
            {id:33,emoji:'assets/img/emojis/emoji33.png'},{id:34,emoji:'assets/img/emojis/emoji34.png'},{id:35,emoji:'assets/img/emojis/emoji35.png'},{id:36,emoji:'assets/img/emojis/emoji36.png'},
            {id:37,emoji:'assets/img/emojis/emoji37.png'},{id:38,emoji:'assets/img/emojis/emoji38.png'},{id:39,emoji:'assets/img/emojis/emoji39.png'},{id:40,emoji:'assets/img/emojis/emoji40.png'},
            {id:41,emoji:'assets/img/emojis/emoji41.png'},{id:42,emoji:'assets/img/emojis/emoji42.png'},{id:43,emoji:'assets/img/emojis/emoji43.png'},{id:44,emoji:'assets/img/emojis/emoji44.png'},
            {id:45,emoji:'assets/img/emojis/emoji45.png'},{id:46,emoji:'assets/img/emojis/emoji46.png'},{id:47,emoji:'assets/img/emojis/emoji47.png'},{id:48,emoji:'assets/img/emojis/emoji48.png'},
            {id:49,emoji:'assets/img/emojis/emoji49.png'},{id:50,emoji:'assets/img/emojis/emoji50.png'},{id:51,emoji:'assets/img/emojis/emoji51.png'},{id:52,emoji:'assets/img/emojis/emoji52.png'},
            {id:53,emoji:'assets/img/emojis/emoji53.png'},{id:54,emoji:'assets/img/emojis/emoji54.png'},{id:55,emoji:'assets/img/emojis/emoji55.png'},{id:56,emoji:'assets/img/emojis/emoji56.png'},
            {id:57,emoji:'assets/img/emojis/emoji57.png'},{id:58,emoji:'assets/img/emojis/emoji58.png'},{id:59,emoji:'assets/img/emojis/emoji59.png'},{id:60,emoji:'assets/img/emojis/emoji60.png'},
            {id:61,emoji:'assets/img/emojis/emoji61.png'},{id:62,emoji:'assets/img/emojis/emoji62.png'},{id:63,emoji:'assets/img/emojis/emoji63.png'},{id:64,emoji:'assets/img/emojis/emoji64.png'},
            {id:65,emoji:'assets/img/emojis/emoji65.png'},{id:66,emoji:'assets/img/emojis/emoji66.png'},{id:67,emoji:'assets/img/emojis/emoji67.png'},{id:68,emoji:'assets/img/emojis/emoji68.png'},
            {id:69,emoji:'assets/img/emojis/emoji69.png'},{id:70,emoji:'assets/img/emojis/emoji70.png'},{id:71,emoji:'assets/img/emojis/emoji71.png'},{id:72,emoji:'assets/img/emojis/emoji72.png'},
            {id:73,emoji:'assets/img/emojis/emoji73.png'},{id:74,emoji:'assets/img/emojis/emoji74.png'},{id:75,emoji:'assets/img/emojis/emoji75.png'},{id:76,emoji:'assets/img/emojis/emoji76.png'},
            {id:77,emoji:'assets/img/emojis/emoji77.png'},{id:78,emoji:'assets/img/emojis/emoji78.png'},{id:79,emoji:'assets/img/emojis/emoji79.png'},{id:80,emoji:'assets/img/emojis/emoji80.png'},
            {id:81,emoji:'assets/img/emojis/emoji81.png'},{id:82,emoji:'assets/img/emojis/emoji82.png'},{id:83,emoji:'assets/img/emojis/emoji83.png'},{id:84,emoji:'assets/img/emojis/emoji84.png'},
            {id:85,emoji:'assets/img/emojis/emoji85.png'},{id:86,emoji:'assets/img/emojis/emoji86.png'},{id:87,emoji:'assets/img/emojis/emoji87.png'},{id:88,emoji:'assets/img/emojis/emoji88.png'},
            {id:89,emoji:'assets/img/emojis/emoji89.png'},{id:90,emoji:'assets/img/emojis/emoji90.png'},{id:91,emoji:'assets/img/emojis/emoji91.png'},{id:92,emoji:'assets/img/emojis/emoji92.png'},
            {id:93,emoji:'assets/img/emojis/emoji93.png'},{id:94,emoji:'assets/img/emojis/emoji94.png'},{id:95,emoji:'assets/img/emojis/emoji95.png'},{id:96,emoji:'assets/img/emojis/emoji96.png'},
            {id:97,emoji:'assets/img/emojis/emoji97.png'},{id:98,emoji:'assets/img/emojis/emoji98.png'},{id:99,emoji:'assets/img/emojis/emoji99.png'},{id:100,emoji:'assets/img/emojis/emoji100.png'},
            {id:101,emoji:'assets/img/emojis/emoji101.png'},{id:102,emoji:'assets/img/emojis/emoji102.png'},{id:103,emoji:'assets/img/emojis/emoji103.png'},{id:104,emoji:'assets/img/emojis/emoji104.png'},
            {id:105,emoji:'assets/img/emojis/emoji105.png'},{id:106,emoji:'assets/img/emojis/emoji106.png'},{id:107,emoji:'assets/img/emojis/emoji107.png'},{id:108,emoji:'assets/img/emojis/emoji108.png'},
            {id:109,emoji:'assets/img/emojis/emoji109.png'},{id:110,emoji:'assets/img/emojis/emoji110.png'},{id:111,emoji:'assets/img/emojis/emoji111.png'},{id:112,emoji:'assets/img/emojis/emoji112.png'},
            {id:113,emoji:'assets/img/emojis/emoji113.png'},{id:114,emoji:'assets/img/emojis/emoji114.png'},{id:115,emoji:'assets/img/emojis/emoji115.png'},{id:116,emoji:'assets/img/emojis/emoji116.png'},
            {id:117,emoji:'assets/img/emojis/emoji117.png'},{id:118,emoji:'assets/img/emojis/emoji118.png'},{id:119,emoji:'assets/img/emojis/emoji119.png'},{id:120,emoji:'assets/img/emojis/emoji120.png'},
            {id:121,emoji:'assets/img/emojis/emoji121.png'},{id:122,emoji:'assets/img/emojis/emoji122.png'},{id:123,emoji:'assets/img/emojis/emoji123.png'},{id:124,emoji:'assets/img/emojis/emoji124.png'},
            {id:125,emoji:'assets/img/emojis/emoji125.png'},{id:126,emoji:'assets/img/emojis/emoji126.png'},{id:127,emoji:'assets/img/emojis/emoji127.png'},{id:128,emoji:'assets/img/emojis/emoji128.png'},
            {id:129,emoji:'assets/img/emojis/emoji129.png'},{id:130,emoji:'assets/img/emojis/emoji130.png'},{id:131,emoji:'assets/img/emojis/emoji131.png'},{id:132,emoji:'assets/img/emojis/emoji132.png'},
            {id:133,emoji:'assets/img/emojis/emoji133.png'},{id:134,emoji:'assets/img/emojis/emoji134.png'},{id:135,emoji:'assets/img/emojis/emoji135.png'},{id:136,emoji:'assets/img/emojis/emoji136.png'},
            {id:137,emoji:'assets/img/emojis/emoji137.png'},{id:138,emoji:'assets/img/emojis/emoji138.png'},{id:139,emoji:'assets/img/emojis/emoji139.png'},{id:140,emoji:'assets/img/emojis/emoji140.png'},
            {id:141,emoji:'assets/img/emojis/emoji141.png'},{id:142,emoji:'assets/img/emojis/emoji142.png'},{id:143,emoji:'assets/img/emojis/emoji143.png'},{id:144,emoji:'assets/img/emojis/emoji144.png'},
            {id:145,emoji:'assets/img/emojis/emoji145.png'},{id:146,emoji:'assets/img/emojis/emoji146.png'},{id:147,emoji:'assets/img/emojis/emoji147.png'},{id:148,emoji:'assets/img/emojis/emoji148.png'},
            {id:149,emoji:'assets/img/emojis/emoji149.png'},{id:150,emoji:'assets/img/emojis/emoji150.png'},{id:151,emoji:'assets/img/emojis/emoji151.png'},{id:152,emoji:'assets/img/emojis/emoji152.png'},
            {id:153,emoji:'assets/img/emojis/emoji153.png'},{id:154,emoji:'assets/img/emojis/emoji154.png'},{id:155,emoji:'assets/img/emojis/emoji155.png'},{id:156,emoji:'assets/img/emojis/emoji156.png'},
            {id:157,emoji:'assets/img/emojis/emoji157.png'},{id:158,emoji:'assets/img/emojis/emoji158.png'},{id:159,emoji:'assets/img/emojis/emoji159.png'},{id:160,emoji:'assets/img/emojis/emoji160.png'},
            {id:161,emoji:'assets/img/emojis/emoji161.png'},{id:162,emoji:'assets/img/emojis/emoji162.png'},{id:163,emoji:'assets/img/emojis/emoji163.png'},{id:164,emoji:'assets/img/emojis/emoji164.png'},
            {id:165,emoji:'assets/img/emojis/emoji165.png'},{id:166,emoji:'assets/img/emojis/emoji166.png'},{id:167,emoji:'assets/img/emojis/emoji167.png'},{id:168,emoji:'assets/img/emojis/emoji168.png'},
            {id:169,emoji:'assets/img/emojis/emoji169.png'},{id:170,emoji:'assets/img/emojis/emoji170.png'},{id:171,emoji:'assets/img/emojis/emoji171.png'},{id:172,emoji:'assets/img/emojis/emoji172.png'},
            {id:173,emoji:'assets/img/emojis/emoji173.png'},{id:174,emoji:'assets/img/emojis/emoji174.png'},{id:175,emoji:'assets/img/emojis/emoji175.png'},{id:176,emoji:'assets/img/emojis/emoji176.png'},
            {id:177,emoji:'assets/img/emojis/emoji177.png'},{id:178,emoji:'assets/img/emojis/emoji178.png'},{id:179,emoji:'assets/img/emojis/emoji179.png'},{id:180,emoji:'assets/img/emojis/emoji180.png'},
            {id:181,emoji:'assets/img/emojis/emoji181.png'},{id:182,emoji:'assets/img/emojis/emoji182.png'},{id:183,emoji:'assets/img/emojis/emoji183.png'},{id:184,emoji:'assets/img/emojis/emoji184.png'},
            {id:185,emoji:'assets/img/emojis/emoji185.png'},{id:186,emoji:'assets/img/emojis/emoji186.png'},{id:187,emoji:'assets/img/emojis/emoji187.png'},{id:188,emoji:'assets/img/emojis/emoji188.png'},
            {id:189,emoji:'assets/img/emojis/emoji189.png'},{id:190,emoji:'assets/img/emojis/emoji190.png'},{id:191,emoji:'assets/img/emojis/emoji191.png'},{id:192,emoji:'assets/img/emojis/emoji192.png'},
            {id:193,emoji:'assets/img/emojis/emoji193.png'},{id:194,emoji:'assets/img/emojis/emoji194.png'},{id:195,emoji:'assets/img/emojis/emoji195.png'},{id:196,emoji:'assets/img/emojis/emoji196.png'},
            {id:197,emoji:'assets/img/emojis/emoji197.png'},{id:198,emoji:'assets/img/emojis/emoji198.png'},{id:199,emoji:'assets/img/emojis/emoji199.png'},{id:200,emoji:'assets/img/emojis/emoji200.png'},
            {id:201,emoji:'assets/img/emojis/emoji201.png'},{id:202,emoji:'assets/img/emojis/emoji202.png'},{id:203,emoji:'assets/img/emojis/emoji203.png'},{id:204,emoji:'assets/img/emojis/emoji204.png'},
            {id:205,emoji:'assets/img/emojis/emoji205.png'},{id:206,emoji:'assets/img/emojis/emoji206.png'},{id:207,emoji:'assets/img/emojis/emoji207.png'},{id:208,emoji:'assets/img/emojis/emoji208.png'},
            {id:209,emoji:'assets/img/emojis/emoji209.png'},{id:210,emoji:'assets/img/emojis/emoji210.png'},{id:211,emoji:'assets/img/emojis/emoji211.png'},{id:212,emoji:'assets/img/emojis/emoji212.png'},
            {id:213,emoji:'assets/img/emojis/emoji213.png'},{id:214,emoji:'assets/img/emojis/emoji214.png'},{id:215,emoji:'assets/img/emojis/emoji215.png'},{id:216,emoji:'assets/img/emojis/emoji216.png'},
            {id:217,emoji:'assets/img/emojis/emoji217.png'},{id:218,emoji:'assets/img/emojis/emoji218.png'},{id:219,emoji:'assets/img/emojis/emoji219.png'},{id:220,emoji:'assets/img/emojis/emoji220.png'},
            {id:221,emoji:'assets/img/emojis/emoji221.png'},{id:222,emoji:'assets/img/emojis/emoji202.png'},{id:223,emoji:'assets/img/emojis/emoji203.png'},{id:224,emoji:'assets/img/emojis/emoji224.png'},
            {id:225,emoji:'assets/img/emojis/emoji225.png'},{id:226,emoji:'assets/img/emojis/emoji206.png'},{id:227,emoji:'assets/img/emojis/emoji207.png'},{id:228,emoji:'assets/img/emojis/emoji228.png'},
            {id:229,emoji:'assets/img/emojis/emoji229.png'},{id:230,emoji:'assets/img/emojis/emoji230.png'},{id:231,emoji:'assets/img/emojis/emoji231.png'},{id:232,emoji:'assets/img/emojis/emoji232.png'},
            {id:233,emoji:'assets/img/emojis/emoji233.png'},{id:234,emoji:'assets/img/emojis/emoji234.png'},{id:235,emoji:'assets/img/emojis/emoji235.png'},{id:236,emoji:'assets/img/emojis/emoji236.png'},
            {id:237,emoji:'assets/img/emojis/emoji237.png'},{id:238,emoji:'assets/img/emojis/emoji238.png'},{id:239,emoji:'assets/img/emojis/emoji239.png'},{id:240,emoji:'assets/img/emojis/emoji240.png'},
            {id:241,emoji:'assets/img/emojis/emoji241.png'},{id:242,emoji:'assets/img/emojis/emoji242.png'},{id:243,emoji:'assets/img/emojis/emoji243.png'},{id:244,emoji:'assets/img/emojis/emoji244.png'},
            {id:245,emoji:'assets/img/emojis/emoji245.png'},{id:246,emoji:'assets/img/emojis/emoji246.png'},{id:247,emoji:'assets/img/emojis/emoji247.png'},{id:248,emoji:'assets/img/emojis/emoji248.png'},
            {id:249,emoji:'assets/img/emojis/emoji249.png'},{id:250,emoji:'assets/img/emojis/emoji250.png'}]
  getEmojis(){
    return this.Emojis
  }
  animals = [{id:1,emoji:'assets/img/Animals/emoji1.png'},{id:2,emoji:'assets/img/Animals/emoji2.png'},{id:3,emoji:'assets/img/Animals/emoji3.png'},{id:4,emoji:'assets/img/Animals/emoji4.png'},
            {id:5,emoji:'assets/img/Animals/emoji5.png'},{id:6,emoji:'assets/img/Animals/emoji6.png'},{id:7,emoji:'assets/img/Animals/emoji7.png'},{id:8,emoji:'assets/img/Animals/emoji8.png'},
            {id:9,emoji:'assets/img/Animals/emoji9.png'},{id:10,emoji:'assets/img/Animals/emoji10.png'},{id:11,emoji:'assets/img/Animals/emoji11.png'},{id:12,emoji:'assets/img/Animals/emoji12.png'},
            {id:13,emoji:'assets/img/Animals/emoji13.png'},{id:14,emoji:'assets/img/Animals/emoji14.png'},{id:15,emoji:'assets/img/Animals/emoji15.png'},{id:16,emoji:'assets/img/Animals/emoji16.png'},
            {id:17,emoji:'assets/img/Animals/emoji17.png'},{id:18,emoji:'assets/img/Animals/emoji18.png'},{id:19,emoji:'assets/img/Animals/emoji19.png'},{id:20,emoji:'assets/img/Animals/emoji20.png'},
            {id:21,emoji:'assets/img/Animals/emoji21.png'},{id:22,emoji:'assets/img/Animals/emoji22.png'},{id:23,emoji:'assets/img/Animals/emoji23.png'},{id:24,emoji:'assets/img/Animals/emoji24.png'},
            {id:25,emoji:'assets/img/Animals/emoji25.png'},{id:26,emoji:'assets/img/Animals/emoji26.png'},{id:27,emoji:'assets/img/Animals/emoji27.png'},{id:28,emoji:'assets/img/Animals/emoji28.png'},
            {id:29,emoji:'assets/img/Animals/emoji29.png'},{id:30,emoji:'assets/img/Animals/emoji30.png'},{id:31,emoji:'assets/img/Animals/emoji31.png'},{id:32,emoji:'assets/img/Animals/emoji32.png'},
            {id:33,emoji:'assets/img/Animals/emoji33.png'},{id:34,emoji:'assets/img/Animals/emoji34.png'},{id:35,emoji:'assets/img/Animals/emoji35.png'},{id:36,emoji:'assets/img/Animals/emoji36.png'},
            {id:37,emoji:'assets/img/Animals/emoji37.png'},{id:38,emoji:'assets/img/Animals/emoji38.png'},{id:39,emoji:'assets/img/Animals/emoji39.png'},{id:40,emoji:'assets/img/Animals/emoji40.png'},
            {id:41,emoji:'assets/img/Animals/emoji41.png'},{id:42,emoji:'assets/img/Animals/emoji42.png'},{id:43,emoji:'assets/img/Animals/emoji43.png'},{id:44,emoji:'assets/img/Animals/emoji44.png'},
            {id:45,emoji:'assets/img/Animals/emoji45.png'},{id:46,emoji:'assets/img/Animals/emoji46.png'},{id:47,emoji:'assets/img/Animals/emoji47.png'},{id:48,emoji:'assets/img/Animals/emoji48.png'},
            {id:49,emoji:'assets/img/Animals/emoji49.png'},{id:50,emoji:'assets/img/Animals/emoji50.png'},{id:51,emoji:'assets/img/Animals/emoji51.png'},{id:52,emoji:'assets/img/Animals/emoji52.png'},
            {id:53,emoji:'assets/img/Animals/emoji53.png'},{id:54,emoji:'assets/img/Animals/emoji54.png'},{id:55,emoji:'assets/img/Animals/emoji55.png'},{id:56,emoji:'assets/img/Animals/emoji56.png'},
            {id:57,emoji:'assets/img/Animals/emoji57.png'},{id:58,emoji:'assets/img/Animals/emoji58.png'},{id:59,emoji:'assets/img/Animals/emoji59.png'},{id:60,emoji:'assets/img/Animals/emoji60.png'},
            {id:61,emoji:'assets/img/Animals/emoji61.png'},{id:62,emoji:'assets/img/Animals/emoji62.png'},{id:63,emoji:'assets/img/Animals/emoji63.png'},{id:64,emoji:'assets/img/Animals/emoji64.png'},
            {id:65,emoji:'assets/img/Animals/emoji65.png'},{id:66,emoji:'assets/img/Animals/emoji66.png'},{id:67,emoji:'assets/img/Animals/emoji67.png'},{id:68,emoji:'assets/img/Animals/emoji68.png'},
            {id:69,emoji:'assets/img/Animals/emoji69.png'},{id:70,emoji:'assets/img/Animals/emoji70.png'},{id:71,emoji:'assets/img/Animals/emoji71.png'},{id:72,emoji:'assets/img/Animals/emoji72.png'},
            {id:73,emoji:'assets/img/Animals/emoji73.png'},{id:74,emoji:'assets/img/Animals/emoji74.png'},{id:75,emoji:'assets/img/Animals/emoji75.png'},{id:76,emoji:'assets/img/Animals/emoji76.png'},
            {id:77,emoji:'assets/img/Animals/emoji77.png'},{id:78,emoji:'assets/img/Animals/emoji78.png'},{id:79,emoji:'assets/img/Animals/emoji79.png'},{id:80,emoji:'assets/img/Animals/emoji80.png'},
            {id:81,emoji:'assets/img/Animals/emoji81.png'},{id:82,emoji:'assets/img/Animals/emoji82.png'},{id:83,emoji:'assets/img/Animals/emoji83.png'},{id:84,emoji:'assets/img/Animals/emoji84.png'},
            {id:85,emoji:'assets/img/Animals/emoji85.png'},{id:86,emoji:'assets/img/Animals/emoji86.png'},{id:87,emoji:'assets/img/Animals/emoji87.png'},{id:88,emoji:'assets/img/Animals/emoji88.png'},
            {id:89,emoji:'assets/img/Animals/emoji89.png'},{id:90,emoji:'assets/img/Animals/emoji90.png'},{id:91,emoji:'assets/img/Animals/emoji91.png'},{id:92,emoji:'assets/img/Animals/emoji92.png'},
            {id:93,emoji:'assets/img/Animals/emoji93.png'},{id:94,emoji:'assets/img/Animals/emoji94.png'},{id:95,emoji:'assets/img/Animals/emoji95.png'},{id:96,emoji:'assets/img/Animals/emoji96.png'},
            {id:97,emoji:'assets/img/Animals/emoji97.png'},{id:98,emoji:'assets/img/Animals/emoji98.png'},{id:99,emoji:'assets/img/Animals/emoji99.png'},{id:100,emoji:'assets/img/Animals/emoji100.png'},
            {id:101,emoji:'assets/img/Animals/emoji101.png'},{id:102,emoji:'assets/img/Animals/emoji102.png'},{id:103,emoji:'assets/img/Animals/emoji103.png'},{id:104,emoji:'assets/img/Animals/emoji104.png'},
            {id:105,emoji:'assets/img/Animals/emoji105.png'},{id:106,emoji:'assets/img/Animals/emoji106.png'},{id:107,emoji:'assets/img/Animals/emoji107.png'},{id:108,emoji:'assets/img/Animals/emoji108.png'},
            {id:109,emoji:'assets/img/Animals/emoji109.png'},{id:110,emoji:'assets/img/Animals/emoji110.png'},{id:111,emoji:'assets/img/Animals/emoji111.png'},{id:112,emoji:'assets/img/Animals/emoji112.png'},
            {id:113,emoji:'assets/img/Animals/emoji113.png'},{id:114,emoji:'assets/img/Animals/emoji114.png'},{id:115,emoji:'assets/img/Animals/emoji115.png'},{id:116,emoji:'assets/img/Animals/emoji116.png'},
            {id:117,emoji:'assets/img/Animals/emoji117.png'},{id:118,emoji:'assets/img/Animals/emoji118.png'},{id:119,emoji:'assets/img/Animals/emoji119.png'},{id:120,emoji:'assets/img/Animals/emoji120.png'},
            {id:121,emoji:'assets/img/Animals/emoji121.png'},{id:122,emoji:'assets/img/Animals/emoji122.png'},{id:123,emoji:'assets/img/Animals/emoji123.png'},{id:124,emoji:'assets/img/Animals/emoji124.png'},
            {id:125,emoji:'assets/img/Animals/emoji125.png'},{id:126,emoji:'assets/img/Animals/emoji126.png'},{id:127,emoji:'assets/img/Animals/emoji127.png'},{id:128,emoji:'assets/img/Animals/emoji128.png'},
            {id:129,emoji:'assets/img/Animals/emoji129.png'},{id:130,emoji:'assets/img/Animals/emoji130.png'},{id:131,emoji:'assets/img/Animals/emoji131.png'},{id:132,emoji:'assets/img/Animals/emoji132.png'},
            {id:133,emoji:'assets/img/Animals/emoji133.png'},{id:134,emoji:'assets/img/Animals/emoji134.png'},{id:135,emoji:'assets/img/Animals/emoji135.png'},{id:136,emoji:'assets/img/Animals/emoji136.png'},
            {id:137,emoji:'assets/img/Animals/emoji137.png'},{id:138,emoji:'assets/img/Animals/emoji138.png'},{id:139,emoji:'assets/img/Animals/emoji139.png'},{id:140,emoji:'assets/img/Animals/emoji140.png'},
            {id:141,emoji:'assets/img/Animals/emoji141.png'},{id:142,emoji:'assets/img/Animals/emoji42.png'},{id:143,emoji:'assets/img/Animals/emoji143.png'},{id:144,emoji:'assets/img/Animals/emoji44.png'},
            {id:145,emoji:'assets/img/Animals/emoji145.png'},{id:146,emoji:'assets/img/Animals/emoji146.png'},{id:147,emoji:'assets/img/Animals/emoji147.png'},{id:148,emoji:'assets/img/Animals/emoji148.png'},
            {id:149,emoji:'assets/img/Animals/emoji149.png'},{id:150,emoji:'assets/img/Animals/emoji150.png'},{id:151,emoji:'assets/img/Animals/emoji151.png'},{id:152,emoji:'assets/img/Animals/emoji152.png'},
            {id:153,emoji:'assets/img/Animals/emoji153.png'},{id:154,emoji:'assets/img/Animals/emoji154.png'},{id:155,emoji:'assets/img/Animals/emoji155.png'},{id:156,emoji:'assets/img/Animals/emoji156.png'},
            {id:157,emoji:'assets/img/Animals/emoji157.png'},{id:158,emoji:'assets/img/Animals/emoji158.png'},{id:159,emoji:'assets/img/Animals/emoji159.png'},{id:160,emoji:'assets/img/Animals/emoji160.png'},
            {id:161,emoji:'assets/img/Animals/emoji161.png'},{id:162,emoji:'assets/img/Animals/emoji162.png'},{id:163,emoji:'assets/img/Animals/emoji163.png'},{id:164,emoji:'assets/img/Animals/emoji164.png'},
            {id:165,emoji:'assets/img/Animals/emoji165.png'},{id:166,emoji:'assets/img/Animals/emoji166.png'},{id:167,emoji:'assets/img/Animals/emoji167.png'},{id:168,emoji:'assets/img/Animals/emoji168.png'},
            {id:169,emoji:'assets/img/Animals/emoji169.png'},{id:170,emoji:'assets/img/Animals/emoji170.png'},{id:171,emoji:'assets/img/Animals/emoji171.png'},{id:172,emoji:'assets/img/Animals/emoji172.png'},
            {id:173,emoji:'assets/img/Animals/emoji173.png'},{id:174,emoji:'assets/img/Animals/emoji174.png'},{id:175,emoji:'assets/img/Animals/emoji175.png'},{id:176,emoji:'assets/img/Animals/emoji176.png'},
            {id:177,emoji:'assets/img/Animals/emoji177.png'},{id:178,emoji:'assets/img/Animals/emoji178.png'},{id:179,emoji:'assets/img/Animals/emoji179.png'},{id:180,emoji:'assets/img/Animals/emoji180.png'},
            {id:181,emoji:'assets/img/Animals/emoji181.png'},{id:182,emoji:'assets/img/Animals/emoji182.png'},{id:183,emoji:'assets/img/Animals/emoji183.png'},{id:184,emoji:'assets/img/Animals/emoji184.png'},
            {id:185,emoji:'assets/img/Animals/emoji185.png'}]
  getAnimals(){
    return this.animals
  }
  eatanddrink = [{id:1,emoji:'assets/img/Eat&Drink/emoji1.png'},{id:2,emoji:'assets/img/Eat&Drink/emoji2.png'},{id:3,emoji:'assets/img/Eat&Drink/emoji3.png'},{id:4,emoji:'assets/img/Eat&Drink/emoji4.png'},
                {id:5,emoji:'assets/img/Eat&Drink/emoji5.png'},{id:6,emoji:'assets/img/Eat&Drink/emoji6.png'},{id:7,emoji:'assets/img/Eat&Drink/emoji7.png'},{id:8,emoji:'assets/img/Eat&Drink/emoji8.png'},
                {id:9,emoji:'assets/img/Eat&Drink/emoji9.png'},{id:10,emoji:'assets/img/Eat&Drink/emoji10.png'},{id:11,emoji:'assets/img/Eat&Drink/emoji11.png'},{id:12,emoji:'assets/img/Eat&Drink/emoji12.png'},
                {id:13,emoji:'assets/img/Eat&Drink/emoji13.png'},{id:14,emoji:'assets/img/Eat&Drink/emoji14.png'},{id:15,emoji:'assets/img/Eat&Drink/emoji15.png'},{id:16,emoji:'assets/img/Eat&Drink/emoji16.png'},
                {id:17,emoji:'assets/img/Eat&Drink/emoji17.png'},{id:18,emoji:'assets/img/Eat&Drink/emoji18.png'},{id:19,emoji:'assets/img/Eat&Drink/emoji19.png'},{id:20,emoji:'assets/img/Eat&Drink/emoji20.png'},
                {id:21,emoji:'assets/img/Eat&Drink/emoji21.png'},{id:22,emoji:'assets/img/Eat&Drink/emoji22.png'},{id:23,emoji:'assets/img/Eat&Drink/emoji23.png'},{id:24,emoji:'assets/img/Eat&Drink/emoji24.png'},
                {id:25,emoji:'assets/img/Eat&Drink/emoji25.png'},{id:26,emoji:'assets/img/Eat&Drink/emoji26.png'},{id:27,emoji:'assets/img/Eat&Drink/emoji27.png'},{id:28,emoji:'assets/img/Eat&Drink/emoji28.png'},
                {id:29,emoji:'assets/img/Eat&Drink/emoji29.png'},{id:30,emoji:'assets/img/Eat&Drink/emoji30.png'},{id:31,emoji:'assets/img/Eat&Drink/emoji31.png'},{id:32,emoji:'assets/img/Eat&Drink/emoji32.png'},
                {id:33,emoji:'assets/img/Eat&Drink/emoji33.png'},{id:34,emoji:'assets/img/Eat&Drink/emoji34.png'},{id:35,emoji:'assets/img/Eat&Drink/emoji35.png'},{id:36,emoji:'assets/img/Eat&Drink/emoji36.png'},
                {id:37,emoji:'assets/img/Eat&Drink/emoji37.png'},{id:38,emoji:'assets/img/Eat&Drink/emoji38.png'},{id:39,emoji:'assets/img/Eat&Drink/emoji39.png'},{id:40,emoji:'assets/img/Eat&Drink/emoji40.png'},
                {id:41,emoji:'assets/img/Eat&Drink/emoji41.png'},{id:42,emoji:'assets/img/Eat&Drink/emoji42.png'},{id:43,emoji:'assets/img/Eat&Drink/emoji43.png'},{id:44,emoji:'assets/img/Eat&Drink/emoji44.png'},
                {id:45,emoji:'assets/img/Eat&Drink/emoji45.png'},{id:46,emoji:'assets/img/Eat&Drink/emoji46.png'},{id:47,emoji:'assets/img/Eat&Drink/emoji47.png'},{id:48,emoji:'assets/img/Eat&Drink/emoji48.png'},
                {id:49,emoji:'assets/img/Eat&Drink/emoji49.png'},{id:50,emoji:'assets/img/Eat&Drink/emoji50.png'},{id:51,emoji:'assets/img/Eat&Drink/emoji51.png'},{id:52,emoji:'assets/img/Eat&Drink/emoji52.png'},
                {id:53,emoji:'assets/img/Eat&Drink/emoji53.png'},{id:54,emoji:'assets/img/Eat&Drink/emoji54.png'},{id:55,emoji:'assets/img/Eat&Drink/emoji55.png'},{id:56,emoji:'assets/img/Eat&Drink/emoji56.png'},
                {id:57,emoji:'assets/img/Eat&Drink/emoji57.png'},{id:58,emoji:'assets/img/Eat&Drink/emoji58.png'},{id:59,emoji:'assets/img/Eat&Drink/emoji59.png'},{id:60,emoji:'assets/img/Eat&Drink/emoji60.png'},
                {id:61,emoji:'assets/img/Eat&Drink/emoji61.png'},{id:62,emoji:'assets/img/Eat&Drink/emoji62.png'},{id:63,emoji:'assets/img/Eat&Drink/emoji63.png'},{id:64,emoji:'assets/img/Eat&Drink/emoji64.png'},
                {id:65,emoji:'assets/img/Eat&Drink/emoji65.png'},{id:66,emoji:'assets/img/Eat&Drink/emoji66.png'},{id:67,emoji:'assets/img/Eat&Drink/emoji67.png'},{id:68,emoji:'assets/img/Eat&Drink/emoji68.png'},
                {id:69,emoji:'assets/img/Eat&Drink/emoji69.png'},{id:70,emoji:'assets/img/Eat&Drink/emoji70.png'},{id:71,emoji:'assets/img/Eat&Drink/emoji71.png'},{id:72,emoji:'assets/img/Eat&Drink/emoji72.png'},
                {id:73,emoji:'assets/img/Eat&Drink/emoji73.png'},{id:74,emoji:'assets/img/Eat&Drink/emoji74.png'},{id:75,emoji:'assets/img/Eat&Drink/emoji75.png'},{id:76,emoji:'assets/img/Eat&Drink/emoji76.png'},
                {id:77,emoji:'assets/img/Eat&Drink/emoji77.png'},{id:78,emoji:'assets/img/Eat&Drink/emoji78.png'},{id:79,emoji:'assets/img/Eat&Drink/emoji79.png'},{id:80,emoji:'assets/img/Eat&Drink/emoji80.png'},
                {id:81,emoji:'assets/img/Eat&Drink/emoji81.png'},{id:82,emoji:'assets/img/Eat&Drink/emoji82.png'},{id:83,emoji:'assets/img/Eat&Drink/emoji83.png'},{id:84,emoji:'assets/img/Eat&Drink/emoji84.png'},
                {id:85,emoji:'assets/img/Eat&Drink/emoji85.png'},{id:86,emoji:'assets/img/Eat&Drink/emoji86.png'},{id:87,emoji:'assets/img/Eat&Drink/emoji87.png'},{id:88,emoji:'assets/img/Eat&Drink/emoji88.png'},
                {id:89,emoji:'assets/img/Eat&Drink/emoji89.png'},{id:90,emoji:'assets/img/Eat&Drink/emoji90.png'},{id:91,emoji:'assets/img/Eat&Drink/emoji91.png'},{id:92,emoji:'assets/img/Eat&Drink/emoji92.png'},
                {id:93,emoji:'assets/img/Eat&Drink/emoji93.png'},{id:94,emoji:'assets/img/Eat&Drink/emoji94.png'},{id:95,emoji:'assets/img/Eat&Drink/emoji95.png'},{id:96,emoji:'assets/img/Eat&Drink/emoji96.png'},
                {id:97,emoji:'assets/img/Eat&Drink/emoji97.png'},{id:98,emoji:'assets/img/Eat&Drink/emoji98.png'},{id:99,emoji:'assets/img/Eat&Drink/emoji99.png'},{id:100,emoji:'assets/img/Eat&Drink/emoji100.png'},
                {id:101,emoji:'assets/img/Eat&Drink/emoji101.png'},{id:102,emoji:'assets/img/Eat&Drink/emoji102.png'},{id:103,emoji:'assets/img/Eat&Drink/emoji103.png'},{id:104,emoji:'assets/img/Eat&Drink/emoji104.png'},
                {id:105,emoji:'assets/img/Eat&Drink/emoji105.png'},{id:106,emoji:'assets/img/Eat&Drink/emoji106.png'},{id:107,emoji:'assets/img/Eat&Drink/emoji107.png'},{id:108,emoji:'assets/img/Eat&Drink/emoji108.png'},
                {id:109,emoji:'assets/img/Eat&Drink/emoji109.png'},{id:110,emoji:'assets/img/Eat&Drink/emoji110.png'},{id:111,emoji:'assets/img/Eat&Drink/emoji111.png'},{id:112,emoji:'assets/img/Eat&Drink/emoji112.png'},
                {id:113,emoji:'assets/img/Eat&Drink/emoji113.png'},{id:114,emoji:'assets/img/Eat&Drink/emoji114.png'},{id:115,emoji:'assets/img/Eat&Drink/emoji115.png'},{id:116,emoji:'assets/img/Eat&Drink/emoji116.png'},
                {id:117,emoji:'assets/img/Eat&Drink/emoji117.png'},{id:118,emoji:'assets/img/Eat&Drink/emoji118.png'},{id:119,emoji:'assets/img/Eat&Drink/emoji119.png'},{id:120,emoji:'assets/img/Eat&Drink/emoji120.png'}]
  getEatings(){
    return this.eatanddrink
  }
  activities = [{id:1,emoji:'assets/img/Activities/emoji1.png'},{id:2,emoji:'assets/img/Activities/emoji2.png'},{id:3,emoji:'assets/img/Activities/emoji3.png'},{id:4,emoji:'assets/img/Activities/emoji4.png'},
                {id:5,emoji:'assets/img/Activities/emoji5.png'},{id:6,emoji:'assets/img/Activities/emoji6.png'},{id:7,emoji:'assets/img/Activities/emoji7.png'},{id:8,emoji:'assets/img/Activities/emoji8.png'},
                {id:9,emoji:'assets/img/Activities/emoji9.png'},{id:10,emoji:'assets/img/Activities/emoji10.png'},{id:11,emoji:'assets/img/Activities/emoji11.png'},{id:12,emoji:'assets/img/Activities/emoji12.png'},
                {id:13,emoji:'assets/img/Activities/emoji13.png'},{id:14,emoji:'assets/img/Activities/emoji14.png'},{id:15,emoji:'assets/img/Activities/emoji15.png'},{id:16,emoji:'assets/img/Activities/emoji16.png'},
                {id:17,emoji:'assets/img/Activities/emoji17.png'},{id:18,emoji:'assets/img/Activities/emoji18.png'},{id:19,emoji:'assets/img/Activities/emoji19.png'},{id:20,emoji:'assets/img/Activities/emoji20.png'},
                {id:21,emoji:'assets/img/Activities/emoji21.png'},{id:22,emoji:'assets/img/Activities/emoji22.png'},{id:23,emoji:'assets/img/Activities/emoji23.png'},{id:24,emoji:'assets/img/Activities/emoji24.png'},
                {id:25,emoji:'assets/img/Activities/emoji25.png'},{id:26,emoji:'assets/img/Activities/emoji26.png'},{id:27,emoji:'assets/img/Activities/emoji27.png'},{id:28,emoji:'assets/img/Activities/emoji28.png'},
                {id:29,emoji:'assets/img/Activities/emoji29.png'},{id:30,emoji:'assets/img/Activities/emoji30.png'},{id:31,emoji:'assets/img/Activities/emoji31.png'},{id:32,emoji:'assets/img/Activities/emoji32.png'},
                {id:33,emoji:'assets/img/Activities/emoji33.png'},{id:34,emoji:'assets/img/Activities/emoji34.png'},{id:35,emoji:'assets/img/Activities/emoji35.png'},{id:36,emoji:'assets/img/Activities/emoji36.png'},
                {id:37,emoji:'assets/img/Activities/emoji37.png'},{id:38,emoji:'assets/img/Activities/emoji38.png'},{id:39,emoji:'assets/img/Activities/emoji39.png'},{id:40,emoji:'assets/img/Activities/emoji40.png'},
                {id:41,emoji:'assets/img/Activities/emoji41.png'},{id:42,emoji:'assets/img/Activities/emoji42.png'},{id:43,emoji:'assets/img/Activities/emoji43.png'},{id:44,emoji:'assets/img/Activities/emoji44.png'},
                {id:45,emoji:'assets/img/Activities/emoji45.png'},{id:46,emoji:'assets/img/Activities/emoji46.png'},{id:47,emoji:'assets/img/Activities/emoji47.png'},{id:48,emoji:'assets/img/Activities/emoji48.png'},
                {id:49,emoji:'assets/img/Activities/emoji49.png'},{id:50,emoji:'assets/img/Activities/emoji50.png'},{id:51,emoji:'assets/img/Activities/emoji51.png'},{id:52,emoji:'assets/img/Activities/emoji52.png'},
                {id:53,emoji:'assets/img/Activities/emoji53.png'},{id:54,emoji:'assets/img/Activities/emoji54.png'},{id:55,emoji:'assets/img/Activities/emoji55.png'},{id:56,emoji:'assets/img/Activities/emoji56.png'},
                {id:57,emoji:'assets/img/Activities/emoji57.png'},{id:58,emoji:'assets/img/Activities/emoji58.png'},{id:59,emoji:'assets/img/Activities/emoji59.png'},{id:60,emoji:'assets/img/Activities/emoji60.png'},
                {id:61,emoji:'assets/img/Activities/emoji61.png'},{id:62,emoji:'assets/img/Activities/emoji62.png'},{id:63,emoji:'assets/img/Activities/emoji63.png'},{id:64,emoji:'assets/img/Activities/emoji64.png'},
                {id:65,emoji:'assets/img/Activities/emoji65.png'},{id:66,emoji:'assets/img/Activities/emoji66.png'},{id:67,emoji:'assets/img/Activities/emoji67.png'},{id:68,emoji:'assets/img/Activities/emoji68.png'},
                {id:69,emoji:'assets/img/Activities/emoji69.png'},{id:70,emoji:'assets/img/Activities/emoji70.png'},{id:71,emoji:'assets/img/Activities/emoji71.png'},{id:72,emoji:'assets/img/Activities/emoji72.png'},
                {id:73,emoji:'assets/img/Activities/emoji73.png'},{id:74,emoji:'assets/img/Activities/emoji74.png'},{id:75,emoji:'assets/img/Activities/emoji75.png'},{id:76,emoji:'assets/img/Activities/emoji76.png'},
                {id:77,emoji:'assets/img/Activities/emoji77.png'},{id:78,emoji:'assets/img/Activities/emoji78.png'},{id:79,emoji:'assets/img/Activities/emoji79.png'},{id:80,emoji:'assets/img/Activities/emoji80.png'},
                {id:81,emoji:'assets/img/Activities/emoji81.png'},{id:82,emoji:'assets/img/Activities/emoji82.png'},{id:83,emoji:'assets/img/Activities/emoji83.png'},{id:84,emoji:'assets/img/Activities/emoji84.png'},
                {id:85,emoji:'assets/img/Activities/emoji85.png'},{id:86,emoji:'assets/img/Activities/emoji86.png'},{id:87,emoji:'assets/img/Activities/emoji87.png'},{id:88,emoji:'assets/img/Activities/emoji88.png'},
                {id:89,emoji:'assets/img/Activities/emoji89.png'},{id:90,emoji:'assets/img/Activities/emoji90.png'}]
  getActivites(){
    return this.activities
  }
}
